baseURL = "https://gg-science.github.io/"
theme = "hugo-bearblog"
title = "Gagan Grewal"
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"

[params]
  description = "Applied data scientist. ML, experimentation, causal inference."
  hideMadeWithLine = true

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = false
    codeFences = true
